const logbookContent = {
    IT: [
      "Assisted in setting up new computer systems for employees, including installing necessary software and configuring network settings.",
      "I learned about basic networking concepts such as IP addressing, subnetting, and network topology during a network setup task.",
      "Participated in troubleshooting hardware issues, including faulty monitors, keyboards, and CPU components, under the guidance of the IT support team.",
      "Gained hands-on experience in managing and updating the company's internal database systems using MySQL and PostgreSQL.",
      "Assisted in monitoring network traffic using tools like Wireshark to identify potential security breaches or unauthorized access.",
      "I learned how to implement basic firewall rules to secure the company's network and prevent external threats.",
      "Helped in managing user accounts on the company’s internal system, including creating new users and resetting passwords for existing users.",
      "Participated in a team project to develop a web application using HTML, CSS, JavaScript, and PHP to streamline internal workflows.",
      "I learned how to perform routine system backups, ensuring that critical data was securely stored and recoverable in case of emergencies.",
      "Assisted in maintaining the company's servers by regularly checking for system updates and applying security patches.",
      "Helped the IT team troubleshoot and resolve issues with the company's VPN, ensuring that remote employees had secure access to internal resources.",
      "I participated in the deployment of an antivirus solution across the company network to safeguard computers from malware and other malicious attacks.",
      "Assisted in creating documentation for software installations, including step-by-step guides for new employees.",
      "I learned how to use command-line tools in Linux for file management, process monitoring, and system diagnostics during a system upgrade task.",
      "Participated in regular IT department meetings where we discussed ongoing projects, troubleshooting strategies, and new technology implementations.",
      "Gained experience in setting up and configuring routers, switches, and other networking devices for internal use.",
      "Helped in creating and managing cloud storage solutions for the company's data, ensuring secure and reliable backups.",
      "Assisted in testing newly developed software applications by conducting usability testing and reporting any bugs or glitches to the development team.",
      "I learned about data encryption techniques used to protect sensitive company information from being accessed by unauthorized users.",
      "Participated in training sessions on cybersecurity best practices, including how to recognize phishing attacks and avoid common security risks.",
      "Assisted in setting up and maintaining the company's local area network (LAN), ensuring connectivity for all devices within the office.",
      "I learned how to configure and manage virtual machines (VMs) using software like VMware for testing and development purposes.",
      "Helped in configuring email accounts and resolving issues with email delivery, spam filters, and email client settings.",
      "Assisted in migrating data from an older system to a new database solution, ensuring that all records were transferred accurately.",
      "I participated in a project to develop a mobile app using React Native, focusing on creating a user-friendly interface for internal staff.",
      "Helped in maintaining the company's IT asset inventory by tracking hardware and software purchases and ensuring proper allocation to employees.",
      "I learned about the process of creating and managing virtual private servers (VPS) for hosting internal applications and services.",
      "Assisted in conducting system performance tests to identify and address bottlenecks, ensuring that company systems operated efficiently.",
      "Gained experience in scripting with Python to automate repetitive tasks such as system monitoring and report generation.",
      "Helped in setting up video conferencing systems for virtual meetings, ensuring proper connectivity and sound quality.",
      "I learned how to use remote desktop software to troubleshoot and resolve IT issues for employees working from home."
    ],
    accounting: [
      "I learned about the process of preparing financial statements, including income statements, balance sheets, and cash flow statements.",
      "Assisted in the preparation of bank reconciliation statements, ensuring all transactions matched the company’s bank records.",
      "Participated in the month-end closing process by recording journal entries and adjusting entries.",
      "Helped in verifying and processing invoices for payment, ensuring all documentation was in order.",
      "Worked with the accounts payable department to record and process supplier payments in a timely manner.",
      "I learned how to use accounting software like QuickBooks and Sage for managing financial records.",
      "Assisted in reviewing and auditing expense reports to ensure compliance with company policies.",
      "Helped with payroll processing by verifying employee timesheets and calculating wages and deductions.",
      "I gained experience in preparing tax returns, including VAT filings and personal income tax computations.",
      "Learned about cost accounting principles and assisted in tracking and analyzing overhead costs for different departments.",
      "Worked on data entry tasks, ensuring all financial transactions were accurately recorded in the ledger.",
      "I learned about the importance of maintaining internal controls and participated in compliance checks.",
      "Assisted in preparing financial reports for management meetings, including profit and loss statements.",
      "Helped in the budgeting process by collecting financial data and inputting it into the budget model.",
      "I gained experience in calculating depreciation of fixed assets and updating the asset register accordingly.",
      "Worked with the accounts receivable team to track outstanding customer balances and send payment reminders.",
      "Helped in calculating financial ratios such as liquidity, profitability, and solvency ratios for performance analysis.",
      "I learned about the process of conducting internal audits and participated in risk assessments.",
      "Assisted in preparing and submitting regulatory reports to government agencies, ensuring compliance with financial regulations.",
      "Participated in analyzing financial data to identify trends and variances from the budget.",
      "I learned about the accounting cycle, from recording transactions to preparing adjusting entries and closing the books.",
      "Helped with preparing trial balances, ensuring that all debits and credits were accurately recorded.",
      "I gained experience in reconciling general ledger accounts and identifying discrepancies in transactions.",
      "Worked with external auditors to provide requested documents and explanations during the audit process.",
      "Helped in managing petty cash by tracking receipts and ensuring all expenses were properly documented.",
      "I learned about the importance of ethics in accounting and the need for transparency and accuracy in financial reporting.",
      "Assisted in preparing cash flow forecasts to help the company manage its liquidity more effectively.",
      "Helped in maintaining accurate records of inventory purchases and calculating cost of goods sold.",
      "I gained experience in managing client accounts, ensuring that all transactions were properly recorded and reconciled.",
      "Participated in financial analysis by reviewing variances between actual and budgeted figures, and suggesting corrective actions."
    ],
    cybersecurity:[
      "Monitored network traffic for potential security breaches and anomalies using intrusion detection tools.",
      "I learned about configuring firewalls to enhance network security and prevent unauthorized access.",
      "Assisted in vulnerability assessments, identifying weaknesses in systems and applications.",
      "Helped update antivirus software and patch vulnerabilities in network systems.",
      "I learned how to review security logs and reports to detect suspicious activity on the network.",
      "Assisted in performing penetration testing under supervision, gaining insight into ethical hacking techniques.",
      "Researched common malware threats and documented ways to mitigate them.",
      "I learned about incident response plans and helped draft steps for handling security breaches.",
      "Helped implement two-factor authentication for better access control across company systems.",
      "Participated in security awareness training, educating employees on best practices for online security.",
      "I learned about the importance of encryption and helped secure sensitive company data.",
      "Worked on access control lists (ACLs) to regulate permissions for users within the network.",
      "Assisted in investigating phishing attempts by analyzing emails and reporting them to senior staff.",
      "I gained an understanding of cloud security policies while helping secure cloud services.",
      "Helped audit user accounts to ensure proper access control and identify inactive accounts for removal.",
      "Monitored and blocked unauthorized IP addresses attempting to access the network.",
      "I learned about developing security policies that align with industry best practices.",
      "Conducted research on emerging cybersecurity threats and their potential impacts on the organization.",
      "Participated in a disaster recovery drill, learning how to respond to major security incidents.",
      "Helped configure virtual private networks (VPNs) for secure remote access to the company's network.",
      "Assisted in implementing data loss prevention (DLP) strategies to safeguard sensitive information.",
      "I learned about securing IoT devices by ensuring proper configuration and monitoring of connected devices.",
      "Helped audit firewall rules to ensure they align with security policies and block unnecessary traffic.",
      "Reviewed the organization's password policies and assisted in recommending stronger security measures.",
      "Assisted in implementing multi-layered security protocols to protect against brute-force attacks.",
      "I learned about wireless network security and helped update encryption methods.",
      "Helped analyze security risks associated with new software implementations and provided recommendations.",
      "Worked on securing API communications by ensuring encrypted and authenticated transmissions.",
      "Assisted in configuring and monitoring security information and event management (SIEM) systems.",
      "I gained insight into reviewing third-party security policies to ensure compliance with organizational standards.",
      "Participated in reviewing endpoint security tools and ensuring all devices had updated protection."
  ],
  TrainingCenters: [
    "Assisted in setting up development environments for Python and Java projects.",
    "Learned how to create basic web pages using HTML and CSS.",
    "Participated in a group project to develop a simple calculator using JavaScript.",
    "Explored version control systems and practiced using Git for collaborative coding.",
    "I learned about the fundamentals of object-oriented programming (OOP) in Python.",
    "Helped in debugging errors in students' code, focusing on logical and syntax issues.",
    "Gained experience in working with APIs by integrating third-party data into a JavaScript project.",
    "I learned how to use CSS frameworks like Bootstrap to design responsive web pages.",
    "Practiced building basic Python scripts to automate simple tasks.",
    "Helped set up databases and performed CRUD operations using SQL and MySQL.",
    "Worked on understanding JavaScript frameworks like React.js and built interactive components.",
    "I learned about data structures such as arrays, linked lists, and dictionaries in Python.",
    "Helped students understand key programming concepts, including loops, conditionals, and functions.",
    "Built and styled a personal portfolio website using HTML, CSS, and JavaScript.",
    "Participated in coding challenges and hackathons to improve problem-solving skills.",
    "I learned about error handling in Python and Java, writing code that manages exceptions properly.",
    "Assisted students with writing algorithms for sorting and searching tasks.",
    "Worked on Java projects, focusing on creating and managing classes and objects.",
    "I learned how to use Python libraries like NumPy and pandas for data analysis.",
    "Explored data science concepts, such as data cleaning, analysis, and visualization using Python.",
    "Assisted in teaching the basics of front-end and back-end development to beginners.",
    "I gained experience in deploying web applications to the cloud using services like Heroku.",
    "Helped students work on simple machine learning models using scikit-learn in Python.",
    "Practiced building RESTful APIs and connecting them to frontend applications.",
    "I learned about responsive design principles and implemented them in web projects.",
    "Assisted in setting up virtual environments and package management for Python projects.",
    "Worked with students to debug and optimize Java code for better performance.",
    "I gained experience in using JavaScript for DOM manipulation and creating interactive web pages.",
    "Participated in reviewing code for projects built by peers, providing feedback and suggestions.",
    "Helped organize workshops on Python programming and web development basics.",
    "I learned how to integrate external libraries and modules into projects for extended functionality."
  ],
  FoodProcessing: [
    "Observed the process of raw material inspection to ensure that incoming ingredients meet the quality standards of the company.",
    "Assisted in the weighing and mixing of ingredients for the production of processed food items such as canned foods and snacks.",
    "Participated in the daily monitoring of production equipment to ensure smooth operation and prevent mechanical failures.",
    "I learned about food safety protocols, including the importance of personal hygiene, proper handling, and storage of raw materials.",
    "Assisted in conducting quality checks during production to ensure the product met the company's standards before packaging.",
    "Helped in monitoring temperature and humidity levels in storage rooms to ensure optimal conditions for preserving raw materials and finished products.",
    "Gained experience in operating food processing machinery, including mixers, grinders, and packaging equipment under supervision.",
    "I learned about the different types of food preservatives used to extend shelf life and how they are applied during production.",
    "Participated in the preparation of production schedules and monitoring of raw material usage to minimize waste.",
    "Helped in tracking and recording the batch numbers of products for quality control and traceability purposes.",
    "I assisted in carrying out sensory evaluations, where we tested the taste, texture, and appearance of finished products for consistency.",
    "Learned about the Hazard Analysis and Critical Control Points (HACCP) system and helped in identifying potential hazards in the production process.",
    "Helped in the packaging process by labeling finished products and ensuring that all information, including expiry dates and batch numbers, was accurate.",
    "I learned how to sanitize equipment and workspaces according to food safety regulations to prevent contamination.",
    "Assisted in testing samples of processed foods in the lab to check for microbial contamination and ensure they were safe for consumption.",
    "Gained experience in maintaining accurate production logs, including data on output, equipment performance, and material usage.",
    "Worked closely with the quality control team to conduct routine inspections of production areas for cleanliness and safety compliance.",
    "Participated in training sessions on Good Manufacturing Practices (GMP) and the importance of adhering to them during the production process.",
    "I observed the process of shelf-life testing, where we monitored how long different food products remained fresh under various conditions.",
    "Assisted in preparing and conducting product sampling for research and development, as the company was exploring new food recipes.",
    "Helped in analyzing production data to identify trends and suggest improvements for increasing efficiency and reducing waste.",
    "I learned about the importance of traceability in the food processing industry and how we tracked each product batch from production to distribution.",
    "Assisted in checking the packaging materials used in production to ensure they were food-safe and durable.",
    "Participated in the cleaning and maintenance of production equipment to minimize downtime and prolong the equipment's lifespan.",
    "Observed how production lines were adjusted to meet different product requirements, such as packaging sizes and ingredient ratios.",
    "Gained experience in recording data on production yields, including the quantity of finished products produced from a given amount of raw materials.",
    "Helped in calculating the nutritional information on food packaging based on ingredient composition and processing methods.",
    "I learned about the importance of supply chain management in ensuring a continuous supply of raw materials and timely delivery of finished products.",
    "Assisted in conducting market research on consumer preferences for new product formulations and flavor profiles.",
    "Participated in the daily health and safety meetings, where we discussed risks and implemented corrective actions to ensure a safe working environment."

  ],
  HospitalLaboratory: [
    "Observed and assisted in the collection of blood samples from patients using sterile techniques to ensure safety and prevent contamination.",
    "Learned how to properly label and store patient samples, ensuring accurate identification for future tests and analysis.",
    "Participated in routine blood tests, including Complete Blood Count (CBC), to assist doctors in diagnosing conditions such as anemia and infections.",
    "Assisted in performing urinalysis, including checking for the presence of proteins, glucose, and signs of infections under supervision.",
    "I learned about the principles of sterile handling during the preparation of culture media for microbiological tests.",
    "Gained hands-on experience in operating centrifuges to separate blood components such as plasma, red blood cells, and platelets for further testing.",
    "Assisted in the calibration of lab equipment, ensuring accurate readings and performance in all diagnostic tests conducted within the lab.",
    "Learned how to properly dispose of biohazard waste materials such as needles, gloves, and other disposable lab items in accordance with safety protocols.",
    "Participated in the preparation of slides for microscopic examination, including blood smears and tissue samples for histopathological review.",
    "Assisted in the identification of pathogens in samples through various staining techniques, such as Gram staining and Ziehl-Neelsen staining.",
    "I learned how to interpret basic test results under the supervision of a lab technician, including identifying abnormalities in blood cell counts.",
    "Gained exposure to ELISA (Enzyme-Linked Immunosorbent Assay) techniques for detecting antibodies and antigens in patient samples.",
    "Assisted in maintaining accurate records of all laboratory tests and patient results in the hospital's database, ensuring confidentiality and accuracy.",
    "Learned the proper procedures for storing reagents and chemicals used in tests to maintain their efficacy and prevent contamination.",
    "Observed and assisted in blood cross-matching procedures for transfusions, ensuring compatibility between donors and recipients.",
    "I gained experience in performing hematology tests, including coagulation tests to assess the clotting ability of patient blood samples.",
    "Assisted in preparing and analyzing microbiological cultures to identify bacterial infections in patient samples.",
    "Learned about the importance of quality control in the laboratory and participated in daily checks to ensure equipment and reagents functioned correctly.",
    "Gained experience in running biochemical tests, including liver function tests, to help diagnose conditions such as hepatitis and liver disorders.",
    "Participated in safety drills and learned about handling spills and accidents involving biohazardous materials to ensure a safe lab environment.",
    "I learned about the role of the laboratory in diagnosing and monitoring chronic diseases, such as diabetes, by performing blood glucose tests.",
    "Assisted in monitoring and maintaining laboratory equipment such as spectrophotometers, ensuring they remained functional and accurate.",
    "Participated in the preparation of reagents for various biochemical and microbiological tests, learning the importance of precise measurements.",
    "Learned how to conduct polymerase chain reaction (PCR) tests under supervision, used to detect and amplify DNA in samples for infectious disease diagnosis.",
    "Assisted in the preparation of reports summarizing test results for submission to physicians, ensuring clarity and accuracy of the data presented.",
    "Gained exposure to diagnostic imaging techniques such as X-rays and MRIs, observing the role of the lab in supporting radiology departments.",
    "Assisted in running electrolyte panels to check levels of key minerals such as sodium and potassium in patient samples.",
    "Learned about blood safety and the screening process for transfusion-transmitted infections, such as HIV and hepatitis.",
    "Participated in the collection and preparation of samples for microbiological cultures to identify pathogens responsible for infections.",
    "Assisted in maintaining sterile environments in the laboratory by regularly cleaning workstations and equipment after each use."

  ],
  Pharmaceuticals: [
    "Observed and assisted in the preparation of pharmaceutical formulations, including tablets and syrups, under the supervision of a pharmacist.",
    "Learned the process of dispensing prescription medications to patients, ensuring accuracy in dosage and instructions while providing relevant drug information.",
    "Gained experience in maintaining proper records for controlled substances, ensuring compliance with legal and regulatory requirements.",
    "Participated in the inventory management of drugs, including checking expiration dates and ensuring proper storage conditions for temperature-sensitive medications.",
    "Assisted in compounding customized medications, such as creams and ointments, for patients with specific needs, following established protocols.",
    "I learned about drug interactions and participated in reviewing patient medications to identify potential conflicts or contraindications.",
    "Gained hands-on experience in filling prescriptions using pharmacy management software, ensuring accuracy in patient records and billing.",
    "Observed how pharmacists counsel patients on proper medication use, including explaining potential side effects and answering patient questions.",
    "Participated in restocking shelves and organizing drugs by classification, ensuring that all medications are easily accessible and properly labeled.",
    "Assisted in the preparation and packaging of blister packs for patients requiring multiple medications on a scheduled basis.",
    "Learned about pharmacovigilance and the monitoring of adverse drug reactions, contributing to the reporting process for any observed side effects.",
    "Gained experience in handling over-the-counter (OTC) drugs, advising customers on the appropriate use of common medications like pain relievers and antihistamines.",
    "I learned about the importance of maintaining patient confidentiality when handling prescriptions and medical information.",
    "Assisted in preparing intravenous (IV) medications in a sterile environment, ensuring proper handling to avoid contamination.",
    "Participated in stock audits and reconciliations to ensure that drug inventories were accurate and in compliance with regulations.",
    "Gained exposure to clinical trials and the role of pharmacists in managing investigational drugs and ensuring patient safety.",
    "Assisted in educating patients on the proper use of medical devices, such as inhalers and insulin pens, to ensure effective administration.",
    "I learned about good manufacturing practices (GMP) and the quality control measures taken to ensure the safety and efficacy of pharmaceutical products.",
    "Observed the process of preparing cytotoxic medications for cancer treatment, ensuring adherence to strict safety protocols.",
    "Assisted in maintaining proper hygiene and cleanliness in the pharmacy to ensure that all medications were handled in a sanitary environment.",
    "Participated in discussions on drug pricing and reimbursement policies, gaining insight into the financial aspects of the pharmaceutical industry.",
    "Gained exposure to the regulatory process for new drug approvals and the role of pharmacists in ensuring compliance with local and international standards.",
    "Assisted in preparing documentation for drug recalls and monitoring products for safety issues or quality concerns.",
    "I learned how to prepare and package prescriptions for home delivery, ensuring accuracy and timeliness in order fulfillment.",
    "Gained experience in counseling patients with chronic conditions such as hypertension and diabetes on proper medication adherence and lifestyle changes.",
    "Assisted in providing immunizations, under supervision, including flu vaccines and other preventive medications, following legal guidelines.",
    "Learned about the role of generic drugs in healthcare and participated in discussions on cost-saving strategies for patients.",
    "Gained experience in preparing patient medication profiles, ensuring a complete history of all prescribed drugs and monitoring for interactions.",
    "Assisted in the education of patients on the importance of completing their antibiotic courses to prevent antibiotic resistance.",
    "Participated in discussions about the impact of new pharmaceutical research on patient care and future treatment options in healthcare."
  ],
  SoftwareEngineering: [
    "Participated in daily stand-up meetings with the development team, gaining insight into Agile project management and sprint planning.",
    "Learned the fundamentals of version control systems (Git) and worked on creating branches and managing repositories for different projects.",
    "Assisted in writing and debugging code for a web application using HTML, CSS, and JavaScript, ensuring the user interface was responsive and functional.",
    "Collaborated with senior developers on designing APIs for data retrieval, understanding how RESTful services are built and consumed in web applications.",
    "I learned about Object-Oriented Programming (OOP) principles and applied them while working on backend services using Python.",
    "Gained experience in writing SQL queries to interact with relational databases, retrieving and updating data based on project requirements.",
    "Worked on unit testing for various software modules using testing frameworks like Jest and Mocha, ensuring the stability of the application.",
    "Assisted in debugging and troubleshooting issues in both the frontend and backend, gaining hands-on experience with browser developer tools and logging services.",
    "Learned about Continuous Integration (CI) and Continuous Deployment (CD) pipelines, and assisted in setting up automated tests and builds using Jenkins.",
    "Contributed to improving the user experience (UX) by providing feedback and suggesting enhancements based on testing and user feedback.",
    "Worked on refactoring existing code to improve performance and maintainability, following coding best practices and standards.",
    "I learned about software design patterns and participated in discussions on how they can be applied to improve the scalability of software solutions.",
    "Participated in code reviews with senior engineers, receiving constructive feedback to improve my coding skills and understanding of best practices.",
    "Gained exposure to cloud computing platforms, such as AWS and Microsoft Azure, and assisted in deploying applications to the cloud.",
    "Assisted in writing technical documentation for new software features, ensuring that both users and developers could easily understand the implementation.",
    "Collaborated with the DevOps team to understand containerization using Docker, and worked on setting up environments for local testing.",
    "I learned about API testing using tools like Postman, testing endpoints for functionality and ensuring that they return the correct responses.",
    "Worked on fixing bugs and enhancing features for mobile applications, gaining insight into Android and iOS development environments.",
    "Assisted in integrating third-party libraries and APIs into software projects, such as payment gateways and social media logins.",
    "Participated in brainstorming sessions on how to improve system performance, focusing on reducing load times and optimizing database queries.",
    "Worked on automating repetitive tasks using scripts written in Python, improving the efficiency of the development workflow.",
    "Learned about software security vulnerabilities such as SQL injection and cross-site scripting (XSS), and assisted in patching these vulnerabilities.",
    "Collaborated with UI/UX designers to translate wireframes and mockups into functional interfaces using frontend technologies.",
    "Gained hands-on experience in writing code for responsive design, ensuring the application worked smoothly across different devices and screen sizes.",
    "I learned about the importance of testing and participated in integration testing for ensuring that different modules worked together seamlessly.",
    "Assisted in developing a chatbot using natural language processing (NLP) libraries and integrating it into an existing web application.",
    "Worked on optimizing the codebase for scalability, focusing on improving memory management and reducing latency in server requests.",
    "Gained experience with Agile tools like Jira, learning how to track project progress, assign tasks, and manage sprints efficiently.",
    "Learned about microservices architecture and participated in discussions on how it can be implemented for scaling large applications.",
    "Assisted in conducting user acceptance testing (UAT) to ensure that the final product met the client’s requirements and functioned as expected.",
    "Worked on integrating authentication services using OAuth and JWT, learning how secure login systems are implemented in modern applications."
  ],
  Banking: [
    "Assisted in the customer service department, learning how to handle customer inquiries, open new accounts, and resolve basic banking issues.",
    "Participated in the daily reconciliation of cash transactions, ensuring that the cash balance matched the records in the system.",
    "Observed the process of loan applications, including the verification of client information, collateral, and credit checks, to understand risk management in lending.",
    "I learned about the different types of accounts, including savings, current, and fixed deposit accounts, and the banking policies associated with each.",
    "Helped in preparing daily financial reports, which provided insights into the bank’s liquidity, profitability, and compliance with regulatory requirements.",
    "Gained exposure to the concept of Know Your Customer (KYC) and assisted in updating customer profiles to comply with anti-money laundering regulations.",
    "I learned about the importance of financial ratios in assessing a bank’s performance, particularly liquidity ratios, capital adequacy, and profitability ratios.",
    "Shadowed the bank’s tellers and learned how to handle cash deposits, withdrawals, and account transfers, while ensuring the accuracy of transactions.",
    "Observed the bank’s risk management department, gaining an understanding of how risks related to credit, liquidity, and operational processes are managed.",
    "Assisted in preparing loan repayment schedules for clients, and gained insights into the different interest rates and repayment terms for various loan types.",
    "Helped in the bank’s marketing efforts by promoting new banking products such as fixed deposits, savings accounts, and mobile banking services to customers.",
    "I learned how the bank ensures compliance with the Central Bank of Nigeria (CBN) regulations, particularly regarding interest rates, reserve requirements, and lending practices.",
    "Assisted in analyzing customer data and financial records to provide the bank’s management with insights into customer behavior and profitability.",
    "Gained exposure to the foreign exchange department, observing how foreign currencies are traded, and how exchange rates impact international transactions.",
    "Helped in the preparation of monthly and quarterly financial reports for management, learning about the key performance indicators used to measure the bank's success.",
    "I learned about the credit analysis process, including how banks assess the creditworthiness of individuals and businesses before approving loans.",
    "Participated in meetings with high-net-worth individuals (HNIs) and corporate clients, gaining insights into relationship management and tailored financial services.",
    "Assisted in the clearing department, learning how cheques are processed and how interbank settlements are carried out through the Nigerian Interbank Settlement System (NIBSS).",
    "I learned about mobile and internet banking services, and how they are transforming traditional banking by making financial transactions more accessible to customers.",
    "Worked with the risk management team to analyze the bank’s credit exposure, learning about stress testing and how to mitigate potential financial losses.",
    "Helped in reviewing and processing loan documentation, ensuring that all terms and conditions were properly outlined before approval.",
    "Assisted in updating and maintaining customer information in the bank’s database, ensuring data accuracy and compliance with data protection regulations.",
    "Observed the treasury department's operations, learning how banks manage liquidity by borrowing and lending money in the interbank market.",
    "I learned about the importance of customer relationship management (CRM) systems in tracking customer interactions and improving customer satisfaction.",
    "Gained exposure to the bank’s investment portfolio, learning how bonds, equities, and other financial instruments are managed to generate returns.",
    "Helped in conducting market research to identify new banking trends, products, and technologies that could improve the bank’s service offerings.",
    "Participated in training sessions on anti-fraud techniques and how banks use technology to detect suspicious transactions and protect against fraud.",
    "Observed how banks use financial ratios and statements to assess a company’s financial health when deciding whether to extend credit.",
    "I learned about the processes involved in mortgage financing, including evaluating property values, down payments, and loan-to-value ratios.",
    "Assisted in promoting the bank’s financial inclusion initiatives, which aim to provide banking services to underserved communities."
  ],
  Hospital: [
    "Observed patient intake procedures, including taking vital signs such as temperature, blood pressure, pulse rate, and respiratory rate, under the supervision of the nursing staff.",
    "Assisted in the preparation and administration of medications to patients, ensuring correct dosages and routes of administration were followed, as prescribed by doctors.",
    "I learned about infection control practices, including proper handwashing techniques, the use of personal protective equipment (PPE), and sterilization of medical instruments.",
    "Assisted in the documentation of patient health records, updating charts with patient histories, lab results, and prescribed treatments for better care coordination.",
    "I learned about the different departments in the hospital, such as the emergency unit, surgical ward, pediatric unit, and intensive care unit (ICU), and their respective roles in patient care.",
    "Participated in patient rounds with doctors, nurses, and other medical staff, observing the evaluation of patient progress and adjustments in treatment plans.",
    "Helped in the outpatient department by taking patients’ vitals and directing them to the appropriate specialist for consultations and follow-up treatments.",
    "I learned how to prepare patients for diagnostic tests such as X-rays, MRI scans, and blood tests, and assisted in explaining procedures to ensure patient comfort and understanding.",
    "Observed various surgical procedures, including pre-operative preparations and post-operative care, learning about surgical tools, sterilization, and patient recovery protocols.",
    "Participated in health promotion activities, providing patients and their families with education on disease prevention, nutrition, and post-hospital care plans.",
    "Assisted the laboratory staff by collecting blood and urine samples from patients and observing the processes involved in testing these samples for different medical conditions.",
    "I learned about triage in the emergency department, understanding how patients are prioritized based on the severity of their conditions to ensure timely care.",
    "Shadowed the hospital's pharmacists, learning about drug interactions, side effects, and the importance of patient counseling when dispensing medications.",
    "Helped the nursing staff with patient mobility, including assisting patients with limited mobility to move around the ward and repositioning bedridden patients to prevent bedsores.",
    "Participated in the hospital's immunization program, observing the administration of vaccines to children and adults, and learning about the importance of immunizations in public health.",
    "I learned how to monitor patients on life-support systems, including ventilators and heart monitors, and assisted in checking the accuracy of these machines.",
    "Assisted in preparing patients for discharge by explaining medication instructions, follow-up care, and scheduled future appointments to ensure continuity of care.",
    "Observed how doctors diagnose various illnesses, learning about common symptoms and conditions such as diabetes, hypertension, and respiratory infections.",
    "I learned about the role of the hospital’s social workers in patient care, particularly in helping patients with chronic conditions access financial assistance and support services.",
    "Shadowed the hospital’s dietitian, learning how nutritional plans are developed for patients based on their medical conditions, such as diabetes or hypertension.",
    "Assisted in maintaining cleanliness and hygiene in patient wards by ensuring proper waste disposal, linen changes, and surface cleaning to reduce the risk of infection.",
    "Observed the hospital’s electronic health record (EHR) system, learning how it is used to store, retrieve, and share patient information across departments securely.",
    "I learned about the importance of teamwork in a hospital setting, observing how doctors, nurses, lab technicians, and administrative staff collaborate to provide comprehensive care.",
    "Assisted in the antenatal clinic, where I learned about prenatal care, including monitoring fetal development, maternal health, and advising expectant mothers on healthy practices.",
    "Participated in patient counseling sessions led by doctors and nurses, gaining insight into how patients are guided through treatment options and the importance of patient education.",
    "Helped in preparing patients for diagnostic procedures like ECGs, ultrasound, and endoscopy, ensuring they were calm and ready for the examination.",
    "Observed how the hospital's laboratory processed samples for infectious diseases like malaria, typhoid, and tuberculosis, learning about the steps involved in accurate diagnosis.",
    "I learned about medical ethics and patient confidentiality, ensuring that patient information is handled discreetly and only shared with authorized personnel.",
    "Assisted in tracking inventory in the hospital pharmacy, helping to maintain adequate supplies of medications and medical equipment for patient care.",
    "Helped in preparing educational materials for a community outreach program, focused on promoting maternal and child health awareness in rural areas."
  ],
  MechanicalEngineering: [
    "Assisted in the assembly and disassembly of mechanical components of industrial machinery, learning about the various parts and their functions.",
    "Observed the maintenance and repair of hydraulic and pneumatic systems used in manufacturing plants, including checking pressure levels and replacing worn-out parts.",
    "Participated in a team tasked with troubleshooting mechanical failures in production equipment, learning how to identify and rectify common issues like misalignment and excessive wear.",
    "I learned about the use of Computer-Aided Design (CAD) software to create and modify technical drawings for mechanical components used in manufacturing.",
    "Shadowed senior engineers during the inspection of equipment to assess performance efficiency and identify areas requiring improvement.",
    "Assisted in performing routine maintenance on diesel engines, including oil changes, filter replacements, and checking the functionality of cooling and lubrication systems.",
    "I learned about the importance of precision measurement tools such as micrometers and calipers, and how they are used to ensure components meet design specifications.",
    "Helped with the design and fabrication of mechanical fixtures for assembly lines, gaining insight into material selection, cost estimation, and manufacturing processes.",
    "Observed and participated in welding processes, including MIG and TIG welding, to join metal components, and learned the importance of proper welding techniques to ensure strength and durability.",
    "I learned about safety protocols in a machine shop environment, including the proper use of Personal Protective Equipment (PPE) and adherence to standard operating procedures.",
    "Assisted in conducting tests on mechanical systems to ensure they met performance and safety standards, such as testing the tensile strength of materials and pressure testing fluid systems.",
    "Shadowed engineers during the calibration of machinery to maintain optimal performance, and participated in adjustments to improve efficiency and reduce downtime.",
    "I learned about thermodynamics principles, particularly how heat transfer affects mechanical systems, by observing cooling systems in engines and heat exchangers in industrial settings.",
    "Helped in conducting failure analysis on damaged mechanical components, learning how stress, fatigue, and material defects contribute to breakdowns.",
    "I learned about the basics of fluid mechanics by assisting in the design and testing of pumps, valves, and piping systems for effective fluid transportation in industrial processes.",
    "Assisted in monitoring and maintaining HVAC (Heating, Ventilation, and Air Conditioning) systems in a commercial building, ensuring proper airflow and temperature control.",
    "Participated in a project focused on reducing energy consumption in a manufacturing plant by optimizing the mechanical systems and improving the efficiency of motors and compressors.",
    "I learned about project management principles, including how to plan, schedule, and allocate resources for the maintenance and repair of mechanical equipment in an industrial setting.",
    "Helped with the fabrication of custom metal parts using lathes and milling machines, gaining hands-on experience with machining operations and quality control.",
    "I learned about the importance of lubrication in mechanical systems, participating in oil analysis and lubrication scheduling to prevent equipment failure due to friction.",
    "Assisted in the installation of new mechanical equipment, including assembling components and ensuring alignment with technical specifications provided by the manufacturers.",
    "Observed the testing of mechanical components under various load conditions to assess durability, and participated in evaluating results to make necessary design modifications.",
    "I learned about the importance of preventive maintenance in prolonging the lifespan of mechanical systems, including how to create maintenance schedules and perform regular system checks.",
    "Helped with the assembly of conveyor systems used in manufacturing, learning about the mechanics of material handling and the importance of proper alignment and tensioning.",
    "Participated in a vibration analysis study on rotating machinery, learning how excessive vibrations can lead to premature failure and how to address them using balancing and damping techniques.",
    "I learned about different types of bearings and their applications in rotating machinery, assisting in the selection and installation of bearings in industrial equipment.",
    "Assisted in the setup of a CNC (Computer Numerical Control) machine, learning how to program the machine for precise cutting and shaping of mechanical parts.",
    "Observed the testing of mechanical seals and gaskets in pressurized systems, ensuring they provide a reliable seal to prevent leaks and maintain system integrity.",
    "I learned about the use of Finite Element Analysis (FEA) software to simulate the behavior of mechanical components under stress, improving designs before fabrication.",
    "Assisted in conducting thermal analysis on mechanical components, learning how to measure and control heat generation in machines to prevent overheating and mechanical failure."
  ],
  ElectricalEngineering: [
    "Assisted in wiring installations for residential and commercial buildings, learning how to follow electrical blueprints and ensure connections meet safety standards.",
    "Participated in the maintenance and troubleshooting of electrical panels, helping to identify and fix issues like short circuits and overloaded breakers.",
    "I learned about the principles of electrical load distribution by observing the balancing of loads across different phases in a three-phase power system.",
    "Assisted in the installation and testing of transformers, ensuring proper insulation and grounding to prevent electrical hazards.",
    "Observed the use of multimeters and oscilloscopes for testing and diagnosing electrical circuits, learning how to measure voltage, current, and resistance.",
    "I learned about the basics of control systems by helping to configure and program PLC (Programmable Logic Controllers) for automation in industrial settings.",
    "Participated in the setup of backup power systems, including installing and maintaining Uninterruptible Power Supply (UPS) systems for critical equipment.",
    "Assisted in the maintenance of electric motors, learning how to check for issues like overheating, worn brushes, and misalignment that can affect performance.",
    "I learned about the importance of proper grounding and bonding in electrical systems to ensure safety and prevent electrical shocks.",
    "Helped install and configure solar panels, gaining insight into renewable energy systems and how they convert sunlight into electricity for residential use.",
    "Shadowed senior engineers in diagnosing faults in power distribution systems, such as identifying and replacing damaged cables and transformers.",
    "Assisted in performing insulation resistance testing on cables and electrical equipment to ensure they meet safety and performance standards.",
    "I learned about the design and installation of lighting systems, including selecting appropriate fixtures, wiring, and switches for both indoor and outdoor applications.",
    "Helped in conducting energy audits in industrial facilities, identifying areas where energy efficiency improvements could be made to reduce electricity consumption.",
    "Observed the installation of circuit breakers and fuses in electrical systems, learning how they protect circuits from overloads and short circuits.",
    "Assisted in the calibration and testing of instrumentation used to monitor electrical systems, such as voltage regulators and power meters.",
    "I learned about the importance of harmonics in electrical systems and how to mitigate their effects to prevent equipment malfunctions and energy losses.",
    "Participated in the testing and commissioning of electrical equipment in a substation, including transformers, circuit breakers, and switchgear.",
    "Helped in the design and installation of a small-scale microgrid system, learning about integrating different power sources like solar and diesel generators.",
    "I learned about the basics of power factor correction, assisting in the installation of capacitor banks to improve power factor and reduce energy losses in industrial facilities.",
    "Assisted in the maintenance and repair of power generators, including checking fuel systems, performing oil changes, and inspecting electrical connections.",
    "Participated in the installation of security systems, including cameras, motion sensors, and alarm systems, and learned about the electrical requirements for these systems.",
    "I learned about high-voltage safety procedures while assisting in the inspection of high-voltage transmission lines, ensuring all work was carried out according to safety protocols.",
    "Helped in the design and installation of an emergency lighting system in a commercial building, ensuring proper backup power and switch-over mechanisms.",
    "Assisted in troubleshooting variable frequency drives (VFDs), learning how to adjust settings and identify faults in motor control applications.",
    "I learned about the importance of surge protection devices and assisted in installing them to protect sensitive equipment from voltage spikes and surges.",
    "Helped in performing power quality analysis in a manufacturing plant, identifying electrical issues such as voltage sags and harmonics affecting equipment performance.",
    "I learned about the use of CAD (Computer-Aided Design) software for drafting electrical layouts and circuit diagrams for building projects.",
    "Assisted in the maintenance of power distribution boards, including cleaning, tightening connections, and replacing damaged fuses and breakers.",
    "Participated in a study on renewable energy integration, learning about the challenges of connecting solar and wind energy systems to the existing power grid."
  ],
  ElectricalEngineering: [
    "Assisted in the installation of electrical wiring systems for a commercial building, including routing cables and ensuring proper insulation to avoid short circuits.",
    "Participated in the troubleshooting of an electrical panel that was tripping, identifying a loose connection in one of the breakers and resolving the issue.",
    "I learned about the functionality and wiring of three-phase motors, including how to connect the motor to a power supply and ensure balanced loading across all phases.",
    "Worked with senior engineers to inspect and maintain power transformers, including testing insulation resistance and performing oil sampling to detect moisture or contamination.",
    "Observed the use of protective relays in power systems, and participated in the testing of relays to ensure they activate correctly in case of overload or short circuit.",
    "I was involved in the design and installation of a small-scale solar power system for a residential area, assisting with the wiring of panels, inverters, and battery storage.",
    "Helped with the maintenance of industrial electric motors, performing tasks such as lubrication, checking brushes, and realigning shafts to improve efficiency and reduce noise.",
    "Learned about the principles of grounding and bonding in electrical installations to ensure system safety, particularly in high-voltage environments.",
    "Worked with a team to install and test Uninterruptible Power Supply (UPS) systems in a data center, ensuring that critical systems have backup power in case of outages.",
    "I learned how to use multimeters and other testing equipment to measure electrical parameters such as voltage, current, and resistance for diagnostics.",
    "Assisted in the installation of emergency lighting systems in a hospital, ensuring that the lights were properly wired to switch over to backup power during outages.",
    "Worked on the design and implementation of an automated lighting system using sensors to control lights based on occupancy, improving energy efficiency.",
    "I was part of a team conducting an energy audit for a manufacturing plant, identifying areas where energy consumption could be reduced, particularly through power factor correction.",
    "Participated in the inspection of high-voltage transmission lines, ensuring that the lines and insulators were in good condition to prevent faults in the distribution system.",
    "Learned about power quality issues such as harmonics, voltage sags, and swells, and assisted in installing equipment to monitor and mitigate these problems.",
    "Worked with senior engineers to install and calibrate voltage regulators in an industrial plant, ensuring stable power supply to sensitive equipment.",
    "I learned how to program and troubleshoot PLCs (Programmable Logic Controllers) used in automation systems, particularly in controlling conveyor belts in a production line.",
    "Assisted in the testing and commissioning of electrical systems in a new office building, including checking wiring integrity, circuit breaker functionality, and power distribution.",
    "Worked on a project to install surge protection devices in a commercial facility, learning how to protect sensitive electronic equipment from voltage spikes.",
    "Helped in the maintenance and repair of electrical substations, including the replacement of aging components such as circuit breakers and transformers.",
    "I learned about the importance of arc flash safety, observing how to perform maintenance on high-voltage equipment while minimizing the risk of electrical accidents.",
    "Participated in the installation of energy-efficient LED lighting systems in an office complex, calculating energy savings and preparing a report for the client.",
    "Worked on a project to install and test Variable Frequency Drives (VFDs) to control the speed of industrial motors, improving energy efficiency in motor-driven systems.",
    "Assisted in the troubleshooting of power distribution boards, identifying issues such as loose connections and overheating that could lead to equipment failures.",
    "I learned about the role of capacitor banks in improving power factor in large industrial systems and helped in their installation and commissioning.",
    "Worked on a solar energy project where I was involved in installing solar panels and connecting them to inverters, ensuring the system met safety and efficiency standards.",
    "Assisted in the design and drafting of electrical layouts for a residential building project using AutoCAD, learning how to create detailed schematics.",
    "Learned about the importance of proper cable sizing and assisted in the selection and installation of cables for a large commercial power distribution project.",
    "I was involved in the maintenance of switchgear, including inspecting and cleaning contacts and ensuring that protective devices such as fuses and relays were functional.",
    "Participated in the setup of a microgrid system that integrates renewable energy sources like solar and wind with conventional generators to provide reliable power to a remote area."
  ],
  ComputerEngineering: [
    "Assisted in the assembly of desktop computers, including installing the motherboard, RAM, CPU, and power supply, and ensuring all components were properly connected.",
    "Participated in troubleshooting a network issue where devices were unable to connect to the internet, identifying the root cause as a misconfigured router.",
    "Learned about how cloud computing works and assisted in setting up a virtual server on Amazon Web Services (AWS) for hosting web applications.",
    "Worked with senior engineers to configure firewalls for a corporate network, ensuring secure access to internal systems and preventing unauthorized access.",
    "Helped in the installation and configuration of Linux operating systems on multiple servers, ensuring all necessary software dependencies were installed and functional.",
    "I was involved in the design of a local area network (LAN) for a small office, including laying out the cable routes and configuring switches and routers for connectivity.",
    "Learned about the process of software version control using Git, and assisted in setting up a repository for collaborative coding and project management.",
    "I learned how to troubleshoot and repair computer hardware issues, including replacing faulty components such as hard drives, power supplies, and graphics cards.",
    "Worked on configuring IP addresses and subnet masks for devices on a company’s network, ensuring proper communication between computers and servers.",
    "I assisted in the development of an embedded system using Arduino, where I programmed a sensor to monitor temperature and send data to a display screen.",
    "Learned about microcontroller programming and wrote code to control the input and output of an embedded device used for automation in a smart home system.",
    "Worked with the software team to optimize a web application by implementing code refactoring techniques, reducing load times and improving overall performance.",
    "I learned about the principles of cybersecurity and helped in conducting a penetration test to identify vulnerabilities in a company’s network and web applications.",
    "Assisted in setting up and configuring virtual machines using VMware to run multiple operating systems on a single physical machine for testing purposes.",
    "I participated in the installation of a backup system using RAID configurations to ensure data redundancy and improve system reliability.",
    "Worked with a senior engineer to design a power supply system for a microcontroller-based project, ensuring stable voltage levels for the device’s operation.",
    "Assisted in setting up and maintaining a server for hosting a database, including configuring the MySQL database management system and ensuring backups were performed regularly.",
    "Helped in the setup of a wireless network in an office building, configuring access points and securing the network with WPA2 encryption.",
    "Learned how to use different debugging tools to identify and resolve issues in software programs, including step-through debugging in integrated development environments (IDEs).",
    "Worked on configuring a Domain Name System (DNS) server to resolve domain names to IP addresses, enabling users to access websites more easily.",
    "I was involved in writing and testing scripts to automate repetitive tasks in a Linux environment, such as file backups and system monitoring.",
    "Assisted in designing a user-friendly interface for a mobile application, collaborating with the UI/UX team to ensure the app's responsiveness across devices.",
    "Participated in building a basic circuit board for an Internet of Things (IoT) project, where sensors gathered data and sent it to a central server for analysis.",
    "I helped set up a remote desktop solution for employees working from home, allowing them to securely access office systems and files from their personal devices.",
    "Learned about database optimization techniques, including indexing and query optimization, to improve the performance of SQL queries in a large-scale system.",
    "I was part of a team that developed a Python script to analyze system logs for security threats, identifying potential breaches and reporting them to the security team.",
    "Assisted in setting up a GitHub repository for a collaborative software project, ensuring proper version control and documentation of the codebase.",
    "Worked on configuring a Continuous Integration/Continuous Deployment (CI/CD) pipeline using Jenkins, automating the process of code deployment to a test environment.",
    "Learned about different file systems, such as NTFS and FAT32, and assisted in formatting and partitioning hard drives for optimal performance.",
    "I participated in setting up a cloud-based database using Firebase for a mobile application, ensuring real-time synchronization of user data across devices.",
    "Helped in troubleshooting connectivity issues between devices on a network, resolving the problem by reconfiguring the network settings and adjusting firewall rules."
  ],
  GraphicsAndWebDesign: [
    "Studied the basic principles of graphic design, including color theory, typography, and composition, to create visually appealing designs.",
    "Learned how to use Adobe Photoshop and Illustrator to design logos, posters, and social media graphics.",
    "Worked on creating wireframes and mockups for a website using Figma, focusing on user-friendly interfaces.",
    "Assisted in designing a responsive website layout, ensuring that the content adjusts to different screen sizes and devices.",
    "Worked on an HTML/CSS project to structure and style web pages, paying attention to web standards and semantic HTML.",
    "Collaborated with the web development team to understand how JavaScript can be used to make websites interactive and dynamic.",
    "Designed and created website banners and promotional materials for online marketing campaigns using Adobe XD.",
    "Participated in a project where I redesigned the company's landing page, improving both aesthetics and functionality.",
    "Assisted in optimizing images for web use, balancing file size and quality to enhance page load speed.",
    "Learned about content management systems (CMS) like WordPress, helping to update and maintain websites.",
    "Helped integrate graphic designs into web pages, ensuring consistency in visual elements across various platforms.",
    "Worked with the team to design an e-commerce website, focusing on the product pages and checkout flow.",
    "Developed my skills in responsive design using frameworks like Bootstrap, ensuring the website looks good on mobile and desktop devices.",
    "Worked on customizing themes and templates for websites using HTML, CSS, and JavaScript.",
    "Learned about SEO (Search Engine Optimization) practices and how to optimize graphics and websites for better search engine rankings.",
    "Designed and optimized icons and buttons for a web application, maintaining brand consistency throughout the project.",
    "Contributed to the redesign of the company’s blog, focusing on enhancing readability and user experience.",
    "Participated in user testing sessions to gather feedback on the design and functionality of a website before launch.",
    "Studied UX/UI principles and applied them to improve the navigation and layout of web pages.",
    "Learned to use Canva and Adobe Spark for creating quick, high-quality social media graphics and marketing content.",
    "Worked on creating website prototypes in Figma, sharing with team members for review and further iteration.",
    "Collaborated with the developers to understand how backend systems interact with front-end designs.",
    "Assisted in the design of an email newsletter template, ensuring it was compatible with various email clients.",
    "Learned about web accessibility standards and helped ensure the website met requirements for users with disabilities.",
    "Designed a portfolio website for showcasing the company's past projects, using HTML, CSS, and some JavaScript for animations.",
    "Explored different fonts and typography trends in web design to improve the readability of the website content.",
    "Created multiple landing pages for different marketing campaigns, focusing on user engagement and call-to-action buttons.",
    "Helped in designing social media posts, ensuring that each design aligned with the company’s branding and messaging.",
    "Developed a responsive image gallery for a client’s website using CSS grid and flexbox techniques.",
    "Created simple animations for web elements using CSS and JavaScript to enhance user interactivity on the site.",
    "Learned how to debug and fix cross-browser compatibility issues to ensure websites work well in all major browsers."
  ],
  
      


    

  };
  
  // Function to randomly pick content for each day
  function getRandomActivities(area) {
    const activities = logbookContent[area];
    const shuffledActivities = [];
  
    // Pick 5 random activities from the array without repeating
    const usedIndices = [];
    for (let i = 0; i < 5; i++) {
      let randomIndex;
      do {
        randomIndex = Math.floor(Math.random() * activities.length);
      } while (usedIndices.includes(randomIndex));
      usedIndices.push(randomIndex);
      shuffledActivities.push(activities[randomIndex]);
    }
  
    return shuffledActivities;
  }
  
  // Function to generate logbook content
  function generateLogbook() {
    const area = document.getElementById('internship-area').value;
    if (area) {
      const [monday, tuesday, wednesday, thursday, friday] = getRandomActivities(area);
      document.getElementById('monday').textContent = monday;
      document.getElementById('tuesday').textContent = tuesday;
      document.getElementById('wednesday').textContent = wednesday;
      document.getElementById('thursday').textContent = thursday;
      document.getElementById('friday').textContent = friday;
  
      // Show the logbook content and the reshuffle button
      document.getElementById('logbook-content').classList.remove('hidden');
      document.getElementById('reshuffle-logbook').classList.remove('hidden');
      document.getElementById('get-report').style.display = 'block';
    } else {
      alert('Please select your internship area.');
    }
  }
  
  // Event listeners for generating and reshuffling the logbook
  document.getElementById('generate-logbook').addEventListener('click', generateLogbook);
  
  document.getElementById('reshuffle-logbook').addEventListener('click', generateLogbook);
  
